### ISSUE TITLE
Needs images for high dpi and retina screens

### ISSUE THREAD

**Issue by Redsandro** [rounders/ember-world-flags#10]
The images look blurry on 4k screens and phones/tablets with a high screen density.

They need a 32px fallback for the 16px images, and a 64px fallback for the 32px images.

I'm not sure how to work with image maps but if it were single images, it would go something like this:

```css
background-image:
  image-set(
    "flag.png" 1x,
    "flag@2x.png" 2x
  );
```

**Comment by rounders** [comment]
@Redsandro the tool that I was using to build the image map unfortunately is no longer available so to address that issue and the issue of higher quality images I have switched to using SVG images in the latest version and those can be displayed in arbitrary sizes. 

eg: the following will display the SVG US flag in 50x50 

```
{{world-flag-svg "us" 50}} 
```

Hopefully the fact that these are SVG will negate the need for the image-set with 2x.

**Comment by Redsandro** [comment]
Thank you for the update @rounders. This is not ideal because it basically drops support for Internet Explorer and pre-chrome Edge, but I guess it's acceptable because we can't keep depending on Microsoft's broken implementations.

**Comment by rounders** [comment]
@Redsandro you are right that it isn't ideal. I did keep the original helper in there too so people can continue to use the png image map if needed.
