### ISSUE TITLE
Incorrect Antarctia Flag

### ISSUE THREAD

**Issue by raemadeline** [rounders/ember-world-flags#11]
The Antarctica flag looks like it doesn't match what's on the wikipedia page: https://en.wikipedia.org/wiki/Flag_of_Antarctica

**Comment by rounders** [comment]
@raemadeline looks like you are right. Thanks for reporting this, I'll get it fixed up this coming weekend.

**Comment by rounders** [comment]
@raemadeline if you update to the latest version (1.1.1) and use the new world-flag-svg helper you'll get the correct Antarctica flag. 

```
{{world-flag-svg "aq"}}
```

**Comment by raemadeline** [comment]
thank you @rounders!
