### ISSUE TITLE
Missing Flags

### ISSUE THREAD

**Issue by elwayman02** [rounders/ember-world-flags#2]
This issue documents flags that are missing from this addon, per the [ISO 3166-1 alpha-2 Spec](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Current_codes).
- [ ] Åland Islands
- [ ] Antarctica
- [ ] Bonaire, Sint Eustatius and Saba
- [ ] Bouvet Island
- [ ] Cocos (Keeling Islands)
- [ ] Saint Barthélemy
- [ ] Christmas Island
- [ ] Costa Rica
- [ ] Curaçao
- [ ] Falkland Islands (Malvinas)
- [ ] French Guiana
- [ ] British Indian Ocean Territory
- [ ] Heard Island and McDonald Islands
- [ ] South Georgia and the South Sandwich Islands
- [ ] Northern Mariana Islands
- [ ] Saint Martin (French part)
- [ ] Niue
- [ ] Norfolk Island
- [ ] Pitcairn
- [ ] Saint Pierre and Miquelon
- [ ] Saint Helena, Ascension and Tristan da Cunha
- [ ] Sint Maarten (Dutch part)
- [ ] South Sudan
- [ ] Svalbard and Jan Mayen
- [ ] French Southern Territories
- [ ] Mayotte
- [ ] Tokelau
- [ ] United States Minor Outlying Islands
- [ ] Wallis and Futuna

**Comment by artsyca** [comment]
On a related note, it would be good to have the option to disable the default US flag display.

**Comment by basz** [comment]
exceptionally reserved

- [ ] European Union

**Comment by kgish** [comment]
+1 EU

**Comment by rounders** [comment]
added all of those missing countries

**Comment by elwayman02** [comment]
:O amazing!
