### ISSUE TITLE
asset folder for production

### ISSUE THREAD

**Issue by bartspiering** [rounders/ember-world-flags#27]
Hi!

It seems that when I build my ember environment a folder with the flag assets is directly created in dist/. Is there a way to manipulate where the assets are stored? I would like to have the images placed in dist/assets/

**Comment by nova-alex** [comment]
What was the resolution to this issue? I have a similar case where `ENV.rootURL` is nested within a subfolder but the assets only work if they're stored at `/`

**Comment by rounders** [comment]
@nova-alex please try version 1.8.0, it should fix your issue.
