### ISSUE TITLE
Not importing "vendor/flags*.css" if used as nested addon

### ISSUE THREAD

**Issue by lordkada** [rounders/ember-world-flags#5]
Hi,
I'm developing an add-on that depends from the `ember-world-flags` package.

When I include `my add-on` in a host application, the `vendor/*.css` files from the `ember-world-flags` (flags16.css and flags32.css) are not copied.

**Comment by rounders** [comment]
@lordkada thanks for the error report. I'll investigate and see what can be done.

**Comment by rounders** [comment]
@lordkada I had a look through https://github.com/ember-cli/ember-cli/issues/3718 which discusses the issue of nested add ons and I just released 0.2.6 which uses one of the workarounds that others have been using and that seems to work well in some of the testing that I did. 

One thing to note is that you'll likely need the following statement inside of your add-on's  included hook:

```javascript
 this._super.included.apply(this, arguments);
```

If you have a chance, please report back and let me know if this fixes your issue.

**Comment by lordkada** [comment]
I will check it tomorrow and let you know... thx ;-)

**Comment by lordkada** [comment]
Yep, it worked... :+1:

**Comment by rounders** [comment]
@lordkada great, thanks for letting me know :smile:
